# Define output file path
$OutputFile = "$env:USERPROFILE\Documents\SystemStats.txt"

# Get System Uptime
$Uptime = (Get-CimInstance Win32_OperatingSystem).LastBootUpTime
$UptimeFormatted = [System.Management.ManagementDateTimeConverter]::ToDateTime($Uptime)

# Get CPU Usage
$CPUUsage = Get-Counter '\Processor(_Total)\% Processor Time' | Select-Object -ExpandProperty CounterSamples | Select-Object -ExpandProperty CookedValue

# Get Memory Usage
$Memory = Get-CimInstance Win32_OperatingSystem
$TotalMemory = [math]::Round($Memory.TotalVisibleMemorySize / 1MB, 2)
$FreeMemory = [math]::Round($Memory.FreePhysicalMemory / 1MB, 2)
$UsedMemory = $TotalMemory - $FreeMemory

# Get Disk Usage
$DiskUsage = Get-PSDrive -PSProvider FileSystem | Select-Object Name, @{Name="Used(GB)"; Expression={[math]::Round($_.Used / 1GB,2)}}, @{Name="Free(GB)"; Expression={[math]::Round($_.Free / 1GB,2)}}

# Get Logged-in User
$User = $env:USERNAME
$ComputerName = $env:COMPUTERNAME

# Get Network Information
$IPAddress = (Get-NetIPAddress | Where-Object { $_.AddressFamily -eq "IPv4" -and $_.InterfaceAlias -notlike "Loopback*" }).IPAddress
$MACAddress = (Get-NetAdapter | Where-Object { $_.Status -eq "Up" }).MacAddress

# Write Data to File
$Report = @"
System Stats Report
-------------------
Date: $(Get-Date)
Computer Name: $ComputerName
Logged-in User: $User

System Uptime: $UptimeFormatted

CPU Usage: $([math]::Round($CPUUsage,2))%

Memory Usage:
  Total Memory: $TotalMemory GB
  Used Memory: $UsedMemory GB
  Free Memory: $FreeMemory GB

Disk Usage:
$(($DiskUsage | Format-Table -AutoSize | Out-String))

Network Information:
  IP Address: $IPAddress
  MAC Address: $MACAddress

-------------------
Generated by PowerShell
"@

$Report | Out-File -FilePath $OutputFile -Encoding UTF8

Write-Output "System stats written to: $OutputFile"